// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhB1kWYyFSwQc75jE92Db8UTTKogWYnjg',
    appId: '1:1063757712434:web:fa69abb833602546e0c02b',
    messagingSenderId: '1063757712434',
    projectId: 'cab-pooling-50cbe',
    authDomain: 'cab-pooling-50cbe.firebaseapp.com',
    storageBucket: 'cab-pooling-50cbe.appspot.com',
    measurementId: 'G-ZEP1J0VCNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjEaLcP2UBPItfI8Pz6WTbFv7bwongxrU',
    appId: '1:1063757712434:android:1becfe8c4be31e54e0c02b',
    messagingSenderId: '1063757712434',
    projectId: 'cab-pooling-50cbe',
    storageBucket: 'cab-pooling-50cbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvLE7SN451Ll1nOjVIVwHsfiKMjxtkLZQ',
    appId: '1:1063757712434:ios:0d680d6811dd3018e0c02b',
    messagingSenderId: '1063757712434',
    projectId: 'cab-pooling-50cbe',
    storageBucket: 'cab-pooling-50cbe.appspot.com',
    iosBundleId: 'com.example.swiftStreet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvLE7SN451Ll1nOjVIVwHsfiKMjxtkLZQ',
    appId: '1:1063757712434:ios:0d680d6811dd3018e0c02b',
    messagingSenderId: '1063757712434',
    projectId: 'cab-pooling-50cbe',
    storageBucket: 'cab-pooling-50cbe.appspot.com',
    iosBundleId: 'com.example.swiftStreet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhB1kWYyFSwQc75jE92Db8UTTKogWYnjg',
    appId: '1:1063757712434:web:ff7586b64add78eae0c02b',
    messagingSenderId: '1063757712434',
    projectId: 'cab-pooling-50cbe',
    authDomain: 'cab-pooling-50cbe.firebaseapp.com',
    storageBucket: 'cab-pooling-50cbe.appspot.com',
    measurementId: 'G-NWERKBXSNB',
  );
}
